#!/usr/bin/env node

'use strict';

const hookUtil = require('./git-hook-utils');

const messageFile = process.argv[2];
const commitSource = process.argv[3];
const sha1 = process.argv[4];

const messageLines = hookUtil.getGitCommitMessageLines(messageFile);
const firstLine = messageLines[0];
const branchName = hookUtil.getBranchName();
const ticketNumber = hookUtil.getTicketNumber(branchName);

const allowedBranch = hookUtil.isAllowedBranch(branchName);
const messageToNotSkip = !hookUtil.isMessageKindToSkip(firstLine);
const ticketNumberAlreadyPresent = firstLine.indexOf(ticketNumber) === 0
const addTicketNumberInfoToCommitMessage = allowedBranch && messageToNotSkip && !ticketNumberAlreadyPresent;
if (addTicketNumberInfoToCommitMessage) {
  messageLines[0] = `${ticketNumber} ${firstLine}`;
  hookUtil.setGitCommitMessageLines(messageFile, messageLines.join('\n'));
} else {
  console.log(`Template not applied for ${branchName}`);
}
