#!/usr/bin/env node

const hookUtil = require('./git-hook-utils');

const messageFile = process.argv[2];
const commitSource = process.argv[3];
const sha1 = process.argv[4];

const messageLines = hookUtil.getGitCommitMessageLines(messageFile);
const firstLine = messageLines[0];
const branchName = hookUtil.getBranchName();

if (hookUtil.isAllowedBranch(branchName) && hookUtil.isValidMessage(firstLine)) {
  const ticketNumber = branchName.split('/').pop();
  if (firstLine.indexOf(ticketNumber) !== 0) {
    messageLines[0] = `${ticketNumber} ${firstLine}`;
    hookUtil.setGitCommitMessageLines(messageFile, messageLines.join('\n'));
  }
} else {
  console.log(`Template not applied for ${branchName} with line ${firstLine}`);
}
